### ISSUE TITLE
定期的に Node の更新を行う

### ISSUE THREAD

**Issue by tchssk** [pacificporter/box-golang-docker#83]
* Go の更新は Dependabot で行なっている
* Dockerfile 内の Node 更新は Dependabot 標準の機能ではできないので仕組みを作る必要がある
* まずは手動でいいので定期的に更新して行った方が良い

**Comment by haruyama** [comment]
https://github.com/pacificporter/kirei/pull/2959 対応作業が必要な場合もあるので, しばらくは 14 系と 16 系を両方保守する必要がありそうです.

**Comment by haruyama** [comment]
16.15.0 がでていた

**Comment by haruyama** [comment]
node v16 だと, 現行の方式での GitHub Actions による Deploy がうまくいかない模様

https://github.com/pacificporter/kirei/runs/6362144449?check_suite_focus=true#step:7:43

root での作業を止める必要がありそう

**Comment by haruyama** [comment]
ヘア/キレイについて node 14 系の現在の最新である 14.20.0 を利用するようになった

**Comment by hfunai** [comment]
v16 対応すすめます

**Comment by hfunai** [comment]
v16 への更新は完了しているのでクローズします。 v18以上が必要になった際にまた作成します。
